language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: C_COMPILER=clang-4.0 CXX_COMPILER=clang++-4.0 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - ninja-build
            - libboost-all-dev

    - os: linux
      dist: trusty
      sudo: false
      env: C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - ninja-build
            - libboost-all-dev

    - os: linux
      dist: trusty
      sudo: false
      env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - ninja-build
            - libboost-all-dev

    - os: linux
      dist: trusty
      sudo: false
      env: C_COMPILER=gcc-7 CXX_COMPILER=g++-7 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
            - libboost-all-dev

    - os: osx
      osx_image: xcode9.3
      env: BUILD_TYPE=Debug


before_install:
  - |
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        brew update
      fi

install:
  ############################################################################
  # Setup default versions and override compiler if needed
  ############################################################################
  - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        if [[ "${C_COMPILER}" != "" ]]; then export CC=${C_COMPILER}; fi
        ${CC} --version

        if [[ "${CXX_COMPILER}" != "" ]]; then export CXX=${CXX_COMPILER}; fi
        ${CXX} --version
      fi

  - |
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        brew install boost
        brew install ninja
      fi

script:
  - mkdir bin
  - cd bin
  - cmake -GNinja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - cmake --build . --target all
  - ctest --verbose

